/**:
  ros__parameters:
    # Network Configuration
    sonar_id: 0
    software_mode: "Evo"  # Options: Evo, EvoC, SeaNet, SeaNetC

    # Frame ID
    frame_id: "gemini_fls" # TF frame ID for sonar data 

    # Default Logging Configuration can also be set via StartSonar service
    log_directory: "/data/gemini"     # Directory to save GLF log files
    log_level: "info"                 # ROS logger level: debug, info, warn, error, fatal
    
    # Sonar Operation 
    range_m: 10.0             # Range in meters (1-120m for 720kHz, 1-50m for 1200kHz)
    gain_percent: 50.0        # Receiver gain 0-100%
    aperture: 120.0           # Sonar aperture in degrees (Switch between: 120 or 65)
    sound_speed_ms: 1500      # Sound speed in m/s
    sound_speed_manual: true  # Sound speed mode: true=manual, false=auto (uses sonar SOS sensor)
    high_resolution: true     # High resolution mode: true=1200kHz (recommended), false=720kHz
    chirp_mode: 2             # Chirp mode: 0=disabled, 1=enabled, 2=auto (recommended)
    
    # Ping Mode 
    ping_free_run: false   # true=continuous (as fast as possible), false=interval-based
    ping_interval_ms: 100  # Ping interval in ms (0-999) when ping_free_run=false. Manual states 5-65Hz (15-200ms) range dpdendnet.
    ping_ext_trigger: false # true=external TTL hardware trigger, false=software controlled
    
    # Topic Names
    topics:
      raw_sonar_image: "gemini/raw_sonar_image"
      projected_sonar_image: "gemini/projected_sonar"
      sonar_detections: "gemini/detections"
      raw_packet: "gemini/raw"
